# 115上 翰版國中 1上 自然 A 版 簡答（逐格照 PDF 簡答頁抄下；每回：A 一（18 題）、A 二 素養題（7 題）、B 部分（9 題））
ANS = {
  1:  ("BCBABADBAA" "BBCBBDAA", "ACBBBAA", "DCABCBABB"),
  2:  ("ADBDBCCBBC" "CABBABDC", "CBCBBBC", "BCCCCDDCC"),
  3:  ("CCBCABDCAC" "BCCBBACA", "BDCCDCA", "BDABACBDC"),
  4:  ("DDADCADACB" "BDDBDCBA", "CDDACBC", "ADABCBDDB"),
  5:  ("BCCADABADC" "CBBCACBD", "CDCCBDA", "BBDBCBBAC"),
  6:  ("CDDBBAADCD" "BABDCDBD", "CBDDCCC", "DCDCABCCD"),
  7:  ("CCDAABDBAC" "AABCCBDB", "CAACAAB", "CBCADBCDA"),
  8:  ("BBDDABDBCC" "BDDCDDCB", "BABADDA", "CBACCDBAD"),
  9:  ("AACDCABBDC" "CDBBADDD", "DDBDACB", "CDCBCADAC"),
  10: ("ABDAABACAA" "BBADBCCD", "BBBCDDA", "CBCABCBCA"),
  11: ("DBBCCCAAAD" "CCBDABDB", "CADBCBA", "DBDBBBDCD"),
  12: ("DBBBCBDCCC" "DDADCBAA", "BCADCAC", "CBCBCBCCA"),
  13: ("CDAABDCDBD" "CDCCDABD", "BCACCDC", "DBCADCBCC"),
  14: ("CAADDBDDDA" "CCDBCCCC", "ABDDDBC", "CCDDDDBAB"),
}
