# 115上 翰版國中 2上 自然 A 版 簡答（逐格照 PDF 簡答頁抄下；每回：A 一（18 題）、A 二 素養題（6～7 題）、B 部分（6～9 題）；題數各回不同，照原卷）
ANS = {
  1:  ("ACBDBBBBDC" "DBBCDDDB", "CBCABAB", "ABDCCC"),
  2:  ("BACDCACABC" "DCAACDBC", "BBDBCAC", "BBDDAB"),
  3:  ("DBDDDDBABC" "ABDBCBAA", "CBADABB", "ABABCD"),
  4:  ("BBACCABBAC" "DBDDDDAA", "BAADCBC", "CBBCCB"),
  5:  ("BBAADDCABB" "CBBCCBAA", "DDBBDA", "CABDADC"),
  6:  ("CCDCADDABD" "BDABCDBD", "ABBBBCC", "BBBBAABBD"),
  7:  ("BBDCDACDCB" "DBAADBCC", "BADABDB", "DBBACDCCA"),
  8:  ("BBABADCBCD" "ACABCABB", "BCCCDCB", "BDDDBC"),
  9:  ("ABABCBDADC" "AADABDCB", "BDDCBAD", "CDBDAA"),
  10: ("BAAABBCCCB" "ADACBADB", "ABCBAAB", "DDBDCBAAC"),
  11: ("CDABBCBBAB" "CBCCBDBB", "CACDAAD", "ADCBCB"),
  12: ("DACBCDBDDC" "ACBBBBAD", "CCCCDAC", "CDDACAADC"),
  13: ("DCBDAACCCC" "DCBCCDCD", "CCCCCCB", "ABABDBDBA"),
  14: ("CBBCBDBBBC" "BDBDCBAC", "ACDCACD", "DBBDDBDAB"),
}
