META = dict(n=2, h1="第2回・Unit 2", subtitle="You Can Learn About Game Design After You Join the Club")
SECTIONS = [
  dict(type="vocab", title="一、文意字彙", meta="18分，每題2分", items=[
    dict(q="The movie was very i___ng. We liked it very much.", answer="interesting"),
    dict(q="Thanks to Mr. Lee, my son learned a lot in his English l___ns.", answer="lessons"),
    dict(q="I can't p___l out the third kitchen drawer（抽屜）. Can you help me, please?", answer="pull"),
    dict(q="A: Is Chinese your favorite s___t? B: Yes. I like Chinese very much.", answer="subject"),
    dict(q="My cousin is a computer e___r. She tests（測試）computers every day.", answer="engineer"),
    dict(q="Sara and I see each other very often because we live on the s___me street.", answer="same"),
    dict(q="A: Did Johnson buy the car? B: No. He couldn't make up his m___d.", answer="mind"),
    dict(q="Today, r___ts can do many things for humans（人類）. They can cook and clean.", answer="robots"),
    dict(q="Candy is not good for your h___th. Don't eat too much, and brush your teeth after you eat it.", answer="health"),
  ]),
  dict(type="mc", title="二、語法選擇", meta="22分，每題2分", items=[
    dict(q="Jenny cried out when she ___ her favorite singer.", options=["see","sees","saw","is seeing"], correct=2),
    dict(q="Always turn off the phone before the movie ___.", options=["start","starts","started","starting"], correct=1),
    dict(q="___ Gale ___ to work, she always eats her breakfast at home.", options=["After; goes","Before; goes","After; went","Before; went"], correct=1),
    dict(q="___ I was young, I ___ a basketball player.", options=["When; am","Before; am","Before; can be","When; was"], correct=3),
    dict(q="___ they exercised, they ___ a shower.", options=["After; took","After; are taking","When; are taking","When; take"], correct=0),
    dict(q="My parents took me ___ a trip ___ Kenting（墾丁）during winter vacation.", options=["to; at","in; from","with; in","on; to"], correct=3),
    dict(q="That green umbrella is Sara's; ___ is yellow.", options=["I","me","my","mine"], correct=3),
    dict(q="The dance teacher is a ___ winner of the World Street Dance Contest.", options=["third","three-time","third time","three times"], correct=1),
    dict(q="Jeff didn't eat any food ___ this morning, so he is very hungry now.", options=["at all","a lot","very much","too much"], correct=0),
    dict(q="A: ___ watch is that? B: It's Kate's.", options=["Who's","What","Which","Whose"], correct=3),
    dict(q="___ car is in the back of the house. ___ is in front of the park.", options=["Yours; Our","Their; Her","His; Theirs","Ours; Yours"], correct=2),
  ]),
  dict(type="mc", title="三、對話選擇", meta="10分，每題2分", items=[
    dict(q="A: Hello. May I speak to Angela, please? B: ___ A: Thanks.", options=["You are welcome.","Hold on, please.","This is she speaking.","Sorry, she is not Angela."], correct=1),
    dict(q="A: Hello. Can I talk to Bruce Miller? B: ___ A: Hi, Mr. Miller. This is Nikita from First Junior High School.", options=["Speaking.","Here you are.","Whose is this?","Where are you from?"], correct=0),
    dict(q="A: Whose jacket is this? B: ___", options=["It's me.","It is a gift.","It's Jason's.","It's a heavy one."], correct=2),
    dict(q="A: Hi. Can I speak to Abby? B: ___ A: This is Lucy.", options=["Please call back.","Who is over there?","Who's calling, please?","Hi, Mr. Lewis. This is Levi."], correct=2),
    dict(q="A: Hello. B: ___ A: Sure.", options=["Yes. Please hold on.","My name is Dan. Nice to meet you.","Sorry. You have the wrong number.","Hi. This is Jessie. May I speak to Lily?"], correct=3),
  ]),
  dict(type="guided-multi", title="四、依提示填入適當的動詞形式", meta="10分，每題2分", items=[
    dict(zh="(eat)", lines=["Before you {{eat}} dinner, please wash your hands first."]),
    dict(zh="(do)", lines=["Vivian often listened to music when she {{did}} her homework."]),
    dict(zh="(read)", lines=["Every day, Alice {{reads}} a book before she goes to bed."]),
    dict(zh="(have)", lines=["Emma always visits her grandfather when she {{has}} time."]),
    dict(zh="(finish)", lines=["After I {{finished}} my homework, I played basketball with my brother."]),
  ]),
  dict(type="guided", title="五、依提示作答", meta="12分，每題4分", items=[
    dict(prompt="Jason cleaned the table after he finished dinner.", hint="（用After...改寫句子）", answer="After Jason finished dinner, he cleaned the table."),
    dict(prompt="The kids went home after they played at the park.", hint="（用... before...改寫句子）", answer="The kids played at the park before they went home."),
    dict(prompt="These postcards are <u>my sister's</u>.", hint="（依畫線部分造原問句）", answer="Whose postcards are those / these?"),
  ]),
  dict(type="translation", title="六、翻譯", meta="12分，每題4分", items=[
    dict(zh="A：這是誰的相機呢？B：這相機是 Ellen 的。", answer="A: Whose camera is this? B: This camera is Ellen's."),
    dict(zh="當我聽到關於足球社的事時，我想起了我的朋友們。", answer="When I heard about the soccer club, I thought of my friends."),
    dict(zh="在中國歷史課結束之後，我就去上了小提琴課。（... after...）", answer="I went to the violin class after the Chinese history class ended."),
  ]),
  dict(type="cloze", title="七、克漏字選擇", meta="8分，每題2分",
    passage="Here are two jokes about phone calls.\n【A】\nTina is a 13-year-old girl. This evening she talked on the phone from 6 to 7 p.m. ___1___ she ended the call, her father said, \"Wow! That was a short ___2___. You usually talk for hours. What happened, dear?\" \"That was the wrong number,\" said Tina.\n【B】\nLeon was lazy today. After he got up, he called his teacher, Mr. Wilson, and said, \"Hello, Mr. Wilson. My little Leon is very sick today, and he can't get up ___3___.\" The teacher at the other end of the phone said, \"___4___\" \"It's my father, sir,\" said Leon.\n\n【字詞】joke 笑話　lazy 懶惰的　sir 先生",
    items=[
      dict(options=["Now","Then","Before","After"], correct=3),
      dict(options=["end","call","start","lesson"], correct=1),
      dict(options=["too","for fun","at all","for free"], correct=2),
      dict(options=["Talk to you later.","Yes, please hold on.","Who is calling, please?","Can you call back later?"], correct=2),
  ]),
  dict(type="reading", title="八、閱讀測驗", meta="8分，每題2分", passages=[
    dict(label="It's Saturday, March 7. Here are today's movies on Film Channel on TV.", text="",
      table=dict(title="", head=["Time","Movie","Time","Movie"], rows=[
        ["12:50 a.m.","Be Ready","1:30 p.m.","Fall in Love"],
        ["2:50 a.m.","Little by Little","3 p.m.","The Sky"],
        ["4:20 a.m.","The Sign","4:50 p.m.","Two Different Lives"],
        ["6 a.m.","Night at the Concert","6:30 p.m.","Black or White"],
        ["8 a.m.","My Name Is Lara","8 p.m.","Night at the Concert"],
        ["10:10 a.m.","The Roberts Family","10 p.m.","Little by Little"],
        ["11:50 a.m.","Everything","11:30 p.m.","Be Ready"]],
        note="【字詞】film 電影　channel 頻道　true 真實的"),
      items=[
        dict(q="When does <i>The Roberts Family</i> start?", options=["At 8 a.m.","At 3 p.m.","At 1:30 p.m.","At 10:10 a.m."], correct=3),
        dict(q="Which movie can people watch on Film Channel when they have lunch?", options=["<i>Everything</i>.","<i>The Sign</i>.","<i>Black or White</i>.","<i>Night at the Concert</i>."], correct=0),
        dict(q="Polly likes the movie <i>Night at the Concert</i>, but she is not free in the evening. When can she watch it?", options=["On the night of March 8.","On the morning of March 8.","On the morning of March 7.","On the afternoon of March 7."], correct=2),
        dict(q="Which may NOT be true?", options=["<i>Fall in Love</i> is about ninety minutes.","The last movie of the day is <i>Be Ready</i>.","<i>My Name Is Lara</i> is on before <i>The Sign</i>.","Film Channel is showing three movies from 1:30 to 6:30 p.m."], correct=2),
      ]),
  ]),
]
