META = dict(n=3, h1="第3回・Review Test 1", subtitle="Unit 1～Unit 2 總複習")
SECTIONS = [
  dict(type="vocab", title="一、文意字彙", meta="20分，每題2分", items=[
    dict(q="The boy f___shed his homework and then went out with his friend.", answer="finished"),
    dict(q="The kids p___led each other's hair when they had a fight.", answer="pulled"),
    dict(q="Manson is not at the office. He is on v___n in Australia.", answer="vacation"),
    dict(q="There is a pop music f___l on the beach. Many people come and enjoy the music.", answer="festival"),
    dict(q="I only waited for twenty minutes for the food after I o___red it on the phone.", answer="ordered"),
    dict(q="My dad is a teacher at a junior high school. He gives English l___ns.", answer="lessons"),
    dict(q="We are talking about something important. Please don't change the s___t.", answer="subject"),
    dict(q="The winter is very cold here; we usually have h___y snow in January and February.", answer="heavy"),
    dict(q="The rainy s___n in India starts in June and ends in October.", answer="season"),
    dict(q="Math is not d___t for Jack at all. He is very good at it.", answer="difficult"),
  ]),
  dict(type="mc", title="二、語法選擇", meta="20分，每題2分", items=[
    dict(q="He showed ___ us a picture of his daughter.", options=["to","of","for","×"], correct=3),
    dict(q="The students wrote a card ___ their teacher on Teachers' Day.", options=["to","on","of","from"], correct=0),
    dict(q="A: Who did you buy these notebooks ___? B: My students.", options=["of","to","for","about"], correct=2),
    dict(q="The jacket over there is mine. Please ___. Thanks.", options=["buy it for me","show it to me","give it to me","make it for me"], correct=2),
    dict(q="These baseball cards are ___. My uncle sent them ___ last week.", options=["mine; me","mine; to me","my; me","mine; with me"], correct=1),
    dict(q="When Stanley ___ free time, he usually played the violin.", options=["has","had","is having","having"], correct=1),
    dict(q="Before I go to bed, I ___ to music.", options=["listen","listened","am listening","listening"], correct=0),
    dict(q="Calvin went out for a walk ___ he ___ his breakfast.", options=["when; has","when; having","after; has","after; had"], correct=3),
    dict(q="A: ___ the weather there? B: It's warm and sunny.", options=["How's","What's","Where's","Who's"], correct=0),
    dict(q="___ is a lot of snow in the mountains in winter.", options=["It","This","There","The weather"], correct=2),
  ]),
  dict(type="mc", title="三、對話選擇", meta="10分，每題2分", items=[
    dict(q="A: Good morning. This is Leo. May I speak to Julian Walker? B: ___ A: Hi, Mr. Walker.", options=["Speaking.","Hold on, please.","Who are you talking to?","You have the wrong number."], correct=0),
    dict(q="A: Hello. Is Sandy there, please? B: ___ A: This is Brian from First Zoo.", options=["Wait a minute.","I am not Sandy.","Sorry, she is not here.","Who is calling, please?"], correct=3),
    dict(q="A: Hello. Is Alex there? B: ___ C: Hello. This is Alex.", options=["Are you Linda?","Yes. Please hold on.","Talk to you later.","Can you call back later?"], correct=1),
    dict(q="A: ___ B: The jacket is Flo's.", options=["Whose jacket is this?","Who bought the jacket?","Why are you wearing a jacket?","Who gave you the jacket?"], correct=0),
    dict(q="A: How is the weather in India today? B: ___", options=["It is rainy today.","It rained for a long time.","It is during the rainy season.","There is a lot of snow in winter."], correct=0),
  ]),
  dict(type="guided-multi", title="四、填入適當的動詞形式", meta="10分，每題2分", items=[
    dict(zh="(wash)", lines=["Jacob {{washes}} his hands before he has breakfast."]),
    dict(zh="(have)", lines=["We walked our dogs before we {{had}} dinner today."]),
    dict(zh="(study)", lines=["Angela seldom listens to music when she {{studies}}."]),
    dict(zh="(get)", lines=["Please brush your teeth after you {{get}} up."]),
    dict(zh="(run)", lines=["Everyone {{ran}} out of the door when the earthquake（地震）happened."]),
  ]),
  dict(type="guided-multi", title="五、依提示寫出所有格代名詞", meta="6分，每格1分", items=[
    dict(zh="(his dad's hair)", lines=["Mike's hair is black, and {{his}} {{dad's}} is brown."]),
    dict(zh="(her history book)", lines=["That is not your history book; it's {{hers}}."]),
    dict(zh="(our bus)", lines=["This bus is not {{ours}}. Our bus is next to the tree."]),
    dict(zh="(your red pen / my red pen)", lines=["The red pen is not {{yours}}; it's {{mine}}."]),
    dict(zh="(Their umbrellas)", lines=["These are not their umbrellas. {{Theirs}} are red and blue."]),
  ]),
  dict(type="guided", title="六、依提示作答", meta="9分，每題3分", items=[
    dict(prompt="This pencil is <u>Betty's</u>.", hint="（依畫線部分造原問句）", answer="Whose pencil is that / this?"),
    dict(prompt="The teacher showed us <u>some nice pictures</u>.", hint="（將畫線部分改成代名詞，改寫句子）", answer="The teacher showed them to us."),
    dict(prompt="Ted went to the guitar club before he studied at the library.", hint="（用After...改寫句子）", answer="After Ted went to the guitar club, he studied at the library."),
  ]),
  dict(type="translation", title="七、翻譯", meta="9分，每題3分", items=[
    dict(zh="她現在不在辦公室裡。請一個小時後再打來。", answer="She is not in the office now. Please call back in an hour."),
    dict(zh="我在寄明信片給你之前，我跟我的朋友踢了足球。（... before...）", answer="I played soccer with my friend(s) before I sent the postcard(s) to you / sent you the postcard(s)."),
    dict(zh="A：上個週末天氣怎麼樣？B：寒冷又颳風。", answer="A: How was the weather last weekend? / What was the weather like last weekend? B: It was cold and windy."),
  ]),
  dict(type="cloze", title="八、克漏字選擇", meta="10分，每題2分",
    passage="Victor: How was your trip to Lucky Island?\nMolly: It was ___1___. My family and I enjoyed the beautiful mountains and lakes on the island.\nVictor: It is often cold and rainy in this season on the island. ___2___ it rain when you were there?\nMolly: ___3___ It was sunny and warm.\nVictor: Just like the weather here.\nMolly: ___4___ Did you do anything special last weekend?\nVictor: Yes. My family and I went to a museum. I have some pictures ___5___ me in the museum. Here.\nMolly: Wow! How cool!",
    items=[
      dict(options=["fun","poor","wrong","strange"], correct=0),
      dict(options=["Is","Was","Did","Does"], correct=2),
      dict(options=["Not at all.","How interesting!","Yes, it was heavy.","We had a good time."], correct=0),
      dict(options=["You know what?","What about you?","Talk to you later.","That's kind of you."], correct=1),
      dict(options=["to","in","of","for"], correct=2),
  ]),
  dict(type="reading", title="九、閱讀測驗", meta="6分，每題2分", passages=[
    dict(label="When Mr. Harden was at work, he got a message on his phone.", text="Hello, Mr. Harden. This is Louisa Foster from Sunny School. There was something wrong with Larry today. Larry usually enjoys soccer, but today he was not happy and didn't play much in PE class. I had a talk with him after class. He cried out to me, \"I hate soccer!\" Now he is in my office. Can you come to school before four o'clock? Please give me a call soon.\n\n【字詞】message 訊息　most likely 最有可能　reply 回覆",
      items=[
        dict(q="What may Louisa Foster be?", options=["A shop clerk.","An engineer.","A school nurse.","A school teacher."], correct=3),
        dict(q="There was something wrong with Larry at school today. What was it?", options=["He didn't enjoy soccer.","He was sick in PE class.","He didn't go to PE class.","He didn't speak to Louisa."], correct=0),
        dict(q="Which is most likely Mr. Harden's reply?", options=["I heard about the soccer club today. I can join the club.","It may be very cold later. Does Larry have his jacket with him?","Thanks for the message. Is he all right now? I can be there before 3 p.m.","What's wrong with Larry? Why couldn't he join soccer games? Can you call me back later?"], correct=2),
      ]),
  ]),
]
