META = dict(n=6, h1="第6回・Unit 4", subtitle="What Do You Want to Be in the Future?")
SECTIONS = [
  dict(type="vocab", title="一、文意字彙", meta="18分，每題2分", items=[
    dict(q="Becoming a s___l NBA player takes（需要）hard work and a lot of practice.", answer="successful"),
    dict(q="Many people here want to be s___rs and fight（奮戰）for their country.", answer="soldiers"),
    dict(q="Leo is in the sixth g___de. This is his last year of elementary school.", answer="grade"),
    dict(q="The weather is nice, so we d___ded to have a picnic at the park.", answer="decided"),
    dict(q="The singer had an i___w with the reporter and answered many questions.", answer="interview"),
    dict(q="I see my r___ves during Chinese New Year. We have big family meals and enjoy our time together.", answer="relatives"),
    dict(q="Archer wants to be a l___r in the future. He wants to fight for people's rights.", answer="lawyer"),
    dict(q="A: I'm so nervous about the contest. B: Don't w___y. You can do it.", answer="worry"),
    dict(q="Carol is the s___y of our boss. She makes coffee, answers phones, and plans the boss's day.", answer="secretary"),
  ]),
  dict(type="mc", title="二、文法選擇", meta="20分，每題2分", items=[
    dict(q="Mia hates ___ the dishes, but she likes cooking.", options=["do","doing","does","did"], correct=1),
    dict(q="The salesman enjoys ___ different people.", options=["meets","to meet","meeting","meet"], correct=2),
    dict(q="The weather is nice today, so we plan ___ a picnic at the park.", options=["have","having","to have","had"], correct=2),
    dict(q="___ a school teacher is not easy because teachers need to plan many lessons.", options=["Be","Being","Is","He's"], correct=1),
    dict(q="I want ___ a dentist when I grow up.", options=["be","being","to be","to"], correct=2),
    dict(q="It's good ___ him ___ the guitar club; he can make many friends there.", options=["to; join","for; joining","to; joining","for; to join"], correct=3),
    dict(q="Ms. Pearson was mad because some students kept ___ in class.", options=["talk","talking","to talk","talked"], correct=1),
    dict(q="My friend and I are talking about ___ a trip to Australia.", options=["take","to take","taking","took"], correct=2),
    dict(q="Toby is an engineer. He is good ___ computers.", options=["to design","at designing","in design","for designing"], correct=1),
    dict(q="We're sorry for ___ fun of you.", options=["making","make","to make","made"], correct=0),
  ]),
  dict(type="guided-multi", title="三、填入適當的動詞形式", meta="6分，每格1分", items=[
    dict(zh="(paint)", lines=["We need {{to paint}} the wall green."]),
    dict(zh="(change)", lines=["David is thinking about {{changing}} jobs."]),
    dict(zh="(watch)", lines=["Lily loves {{watching/to watch}} the movies on Channel 70."]),
    dict(zh="(sing)", lines=["The little boy doesn't want {{to sing}} on stage."]),
    dict(zh="(speak)", lines=["We practice {{speaking}} English every day."]),
    dict(zh="(write)", lines=["I finished {{writing}} the report at 7:30 p.m."]),
  ]),
  dict(type="guided-multi", title="四、看圖回答問題", meta="6分，每格1分", image="images/test6c/sec4_pics.png", items=[
    dict(zh="圖 1", lines=["A: What does Ken do? B: He is a {{dentist}}. He fixes people's {{teeth}}."]),
    dict(zh="圖 2", lines=["A: What does Jay want to be when he grows up? B: He wants to be a {{reporter}}."]),
    dict(zh="圖 3", lines=["The {{salesman}} makes money by selling phones."]),
    dict(zh="圖 4", lines=["The girl has {{butterflies}} in her {{stomach}} when she rides a horse."]),
  ]),
  dict(type="guided", title="五、依提示作答", meta="12分，每題4分", items=[
    dict(prompt="Mr. Warner <u>hates</u> to be a mail carrier.", hint="（畫線部分用enjoy改寫）", answer="Mr. Warner enjoys being a mail carrier."),
    dict(prompt="It is important. We drink enough water.", hint="（用It... to...合併句子）", answer="It is important for us to drink enough water."),
    dict(prompt="I want to thank you. You helped me.", hint="（用I want to thank you for...合併句子）", answer="I want to thank you for helping me."),
  ]),
  dict(type="translation", title="六、翻譯", meta="12分，每題3分", items=[
    dict(zh="我們很難相信這個計畫。（It...）", answer="It is difficult for us to believe in the plan."),
    dict(zh="當一個頂尖的業務是 Nick 的夢想。（V-ing...）", answer="Being a top salesman is Nick's dream."),
    dict(zh="我未來想要製作一部有關農夫的影片。", answer="I want to make a video about farmers in the future."),
    dict(zh="孩子們取笑那個男孩，因為他戴了一個奇怪的面具。（The kids...）", answer="The kids made fun of the boy because he put on / wore / was wearing a strange mask."),
  ]),
  dict(type="cloze", title="七、克漏字選擇", meta="14分，每題2分",
    passage="Mikhail Baryshnikov is a top ballet dancer in ballet history. He has fans ___1___ the world. When he was little, his mom often took him to art shows. He fell in love with ballet after he ___2___ a ballet show. ___3___, his mom died when he was only eleven years old. At the age of 12, he decided ___4___ his ballet studies in a ballet school. When he was 18, he joined the Kirov Ballet in Russia and was successful there.\nIn 1974, he left Russia and moved to the USA. He joined the American Ballet Theatre and ___5___ a top dancer. He was famous for his jumps, and everyone loved his ballet. In 1977, he ___6___ in a movie for the first time—<i>The Turning Point</i>—and later in another one—<i>White Nights</i>. Both were very successful. Today, he has his own dance company and ___7___ teaching young dancers. He is still a big name in the dance world.\n\n【字詞】ballet 芭蕾舞　Russia 俄羅斯　theatre 劇院",
    items=[
      dict(options=["by","into","besides","all over"], correct=3),
      dict(options=["watches","watched","watching","to watch"], correct=1),
      dict(options=["Sadly","Usually","Finally","By the way"], correct=0),
      dict(options=["begin","began","to begin","beginning"], correct=2),
      dict(options=["become","became","becoming","to become"], correct=1),
      dict(options=["acted","grew","found","drove"], correct=0),
      dict(options=["plans","needs","keeps","wants"], correct=2),
  ]),
  dict(type="reading", title="八、閱讀測驗", meta="12分，每題3分", passages=[
    dict(label="", text="    Last month, Anderson's Junior High School had a survey to find out about their students' dream job. Eight hundred students did the survey. There were ten jobs for the students to choose from. Here are the results:\n\n【字詞】survey 問卷　choose 選擇　result 結果　most 最…　least 最不…　infer 推論", image="images/test6c/r_pie.png",
      items=[
        dict(q="Which job is the most popular?", options=["Singer.","Reporter.","Secretary.","Computer engineer."], correct=3),
        dict(q="Which job is the least popular?", options=["Farmer.","Soldier.","Mail carrier.","Factory worker."], correct=3),
        dict(q="How many students want to be a secretary?", options=["112.","120.","128.","160."], correct=1),
        dict(q="What can we infer from the results?", options=["Some students want to teach.","No one likes to work on a farm.","No one wants to be an office worker.","Many students enjoy delivering mail."], correct=0),
      ]),
  ]),
]
