META = dict(n=9, h1="第9回・Unit 5", subtitle="How Do We Go to the Hotel?")
SECTIONS = [
  dict(type="vocab", title="一、文意字彙", meta="20分，每題2分", items=[
    dict(q="A: I'm going to the s___t. What can I get for you? B: Some oranges and a bottle of milk, please.", answer="supermarket"),
    dict(q="The shop is on the c___r of the street. You can see it when you get to the end of the street. It's on the right.", answer="corner"),
    dict(q="I usually ride my s___r to work, but I took the metro today because it was rainy.", answer="scooter"),
    dict(q="Don't swim in the river. That's not safe. Let's swim in the swimming p___l.", answer="pool"),
    dict(q="Maya has long s___t hair. She never curls（捲曲）her hair.", answer="straight"),
    dict(q="Because of the strong wind, the plane is still on the g___d. It cannot leave now.", answer="ground"),
    dict(q="My grandma fell down and broke her legs this morning, so she is now in the h___l.", answer="hospital"),
    dict(q="Allen enjoys going s___ling, so he bought a boat. Now, he is at sea every weekend.", answer="sailing"),
    dict(q="Learning to ride a bike was a terrible e___ce for me. I kept falling off my bike.", answer="experience"),
    dict(q="We walked along the river bank for a___d fifteen minutes and then stopped for a rest.", answer="around"),
  ]),
  dict(type="mc", title="二、文法選擇", meta="20分，每題2分", items=[
    dict(q="A: ___ we go to First Bank? B: We can take the bus.", options=["What did","Where can","How do","Why do"], correct=2),
    dict(q="A: Where is Room 521? B: Go ___ the stairs and turn right. It's ___ your right.", options=["up; on","down; in","for; on","in; of"], correct=0),
    dict(q="The Four Seasons Hotel is ___ the corner ___ Maple Road and Becker Street.", options=["in; at","on; of","of; on","with; from"], correct=1),
    dict(q="A: ___ do you usually go to school? B: My father drives me there.", options=["Why","When","How","Where"], correct=2),
    dict(q="There is no bus stop near the temple. Let's ___ a taxi there.", options=["have","go","make","take"], correct=3),
    dict(q="The park is close to our house. Let's go there on ___.", options=["bus","car","foot","motorcycle"], correct=2),
    dict(q="I was busy ___ on my computer when the clock hit six.", options=["work","worked","working","to work"], correct=2),
    dict(q="There isn't an airport on the island. People can go there only ___ ship.", options=["by","with","on","of"], correct=0),
    dict(q="The bookstore is on ___ floor. Just go up the stairs.", options=["two","the two","second","the second"], correct=3),
    dict(q="It was hot during our bike ride, so we stopped ___ cold drinks at a drink shop.", options=["had","have","having","to have"], correct=3),
  ]),
  dict(type="guided-multi", title="三、看圖完成句子", meta="15分，每格1分", image="images/test9c/sec3_map.png", items=[
    dict(zh="", lines=["The bus stop is {{next}} to the bookstore."]),
    dict(zh="", lines=["Rosa's Restaurant is {{across}} {{from}} the post office."]),
    dict(zh="", lines=["The department store is {{between}} the bus stop and the bank."]),
    dict(zh="", lines=["The bank is {{on}} the {{corner}} {{of}} Third Road and Sun Street."]),
    dict(zh="Q: Susan is in front of the movie theater. How can she get to the train station?", lines=["A: She can go {{down/along}} Sun Street and turn {{left}} {{on}} Third Road."]),
    dict(zh="Q: Jacob is near the museum. How can he get to the hotel?", lines=["A: He can turn {{right}} on Sun Street and walk {{straight}} {{for}} one block. Then he needs to {{turn}} left on Second Road. The hotel is {{on}} his left, behind Rosa's Restaurant."]),
  ]),
  dict(type="guided", title="四、依提示作答", meta="9分，每題3分", items=[
    dict(prompt="I <u>rode a bicycle</u> to my mom's office this afternoon.", hint="（依畫線部分造原問句）", answer="How did you go to your mom's office this afternoon?"),
    dict(prompt="I walked to the movie theater yesterday.", hint="（用I went... 改寫）", answer="I went to the movie theater on foot yesterday."),
    dict(prompt="Sara went to meet her friends by bus.", hint="（用take改寫交通方式）", answer="Sara took a bus to meet her friends."),
  ]),
  dict(type="translation", title="五、翻譯", meta="12分，每題3分", items=[
    dict(zh="我的阿姨會駕駛飛機。", answer="My aunt can fly a plane / an airplane."),
    dict(zh="和朋友一起去衝浪很棒。（It...）", answer="It is wonderful / great to go surfing with friends. / It is wonderful / great to surf with friends."),
    dict(zh="那間玩具店在一間警察局的對面。", answer="The toy store / shop is across from a police station."),
    dict(zh="當 Mia 的爸爸打來時，她正忙著在市場購物。（... when...）", answer="Mia was busy shopping at the market when her father / dad called (her)."),
  ]),
  dict(type="cloze", title="六、克漏字選擇", meta="12分，每題2分",
    passage="Pete: We're back on Park Road again.\nIvy: Oh no, we're ___1___. Let's ask someone ___2___.\nPete: Okay.\n(They see a man.)\nPete: ___3___ Is there a night market on Green Street?\nMan: Yes, there is one there.\nPete: ___4___\nMan: Go down the road and turn right on Second Street. Go along Second Street ___5___ two blocks, and then turn left on Green Street. The night market is on your right.\nIvy: Is it near here?\nMan: It's a twenty-minute walk. You can also take Bus 1 over there. Then ___6___ at the Holiday Hotel.\nIvy: Thank you very much.",
    items=[
      dict(options=["lost","strange","difficult","wonderful"], correct=0),
      dict(options=["help","for help","with help","and help"], correct=1),
      dict(options=["Goodbye.","Oh, right.","Excuse me.","What's up?"], correct=2),
      dict(options=["When were you there?","How did you go there?","How can we get there?","What can we do there?"], correct=2),
      dict(options=["in","for","to","with"], correct=1),
      dict(options=["get on","get off","put on","turn off"], correct=1),
  ]),
  dict(type="reading", title="七、閱讀測驗", meta="12分，每題3分", passages=[
    dict(label="", text="    Timmy is a ten-year-old boy. Yesterday, after he finished his basketball practice at 4 p.m., he went to a new drink shop with his friend. They had cool drinks and talked with each other for about one and a half hours there. After they said goodbye to each other, Timmy was lost—he couldn't find his way home. Luckily, he saw a police station, so he went in and asked a police officer for help.\n    \"Excuse me, sir. I'm lost. Could you please show me the way home? My house is behind First High School, between the library and the park,\" said Timmy.\n    \"No problem. Let's go,\" said the police officer.\n    The police officer took him home in his police car. After fifteen minutes, the police officer found his home. His mother thanked the officer for his help.\n\n【字詞】true 真實的", image="images/test9c/r_map.png",
      items=[
        dict(q="Which is NOT true about Timmy?", options=["He went home in a police car yesterday.","He practiced basketball after school yesterday.","He went to the drink shop with his friend yesterday.","He went home right after basketball practice yesterday."], correct=3),
        dict(q="Why did Timmy go to the police station?", options=["He couldn't find his way home.","He wanted to use the bathroom.","He liked talking to the police officers.","His mother worked in the police station."], correct=0),
        dict(q="Which is the library?", options=["A.","B.","C.","D."], correct=0),
        dict(q="How did the police officer take Timmy home from the police station?", options=["They went down Hill Street and turned left on Banana Road. Then they went straight for two blocks and turned right.","They went straight for one block and turned left on Apple Road. Then they went straight for two blocks and turned left.","They went straight for two blocks and turned left on Orange Road. Then they went straight for one block and turned right.","They went straight for three blocks and turned left on Banana Road. Then they went straight for one block and turned right."], correct=2),
      ]),
  ]),
]
