META = dict(n=11, h1="第11回・Review Test 3", subtitle="Unit 5～Unit 6 總複習")
SECTIONS = [
  dict(type="vocab", title="一、文意字彙", meta="20分，每題2分", items=[
    dict(q="It is w___l to have so many good friends like you guys. Spending time with you is a lot of fun.", answer="wonderful"),
    dict(q="Alex likes to wear sh___ts in summer because long pants are too warm for him.", answer="shorts"),
    dict(q="We saw many flowers on the g___d because they fell from the trees after the heavy rain.", answer="ground"),
    dict(q="I usually buy fruit and milk at the s___t near my place. Many people go there to buy food for the week.", answer="supermarket"),
    dict(q="We went to an e___ve restaurant for dinner last night. The food was yummy, but the prices were too high.", answer="expensive"),
    dict(q="You need to wear a b___t. This way, your pants won't fall down.", answer="belt"),
    dict(q="The children couldn't stop laughing（笑）because the show was very f___y.", answer="funny"),
    dict(q="On weekends, my daughter and I enjoy taking a walk along the river b___k. We can see boats along the way.", answer="bank"),
    dict(q="A: How much was the meal in t___l? B: It was about two thousand dollars.", answer="total"),
    dict(q="The m___le is tall and heavy, so it can be difficult for some people to ride.", answer="motorcycle"),
  ]),
  dict(type="mc", title="二、文法選擇", meta="22分，每題2分", items=[
    dict(q="The ride to the theater ___ about an hour.", options=["spent","cost","took","got"], correct=2),
    dict(q="My sister spent one hour ___ these pictures.", options=["took","taking","to take","for taking"], correct=1),
    dict(q="A: Excuse me. Is there a hospital around here? B: Yes. Just walk ___ two blocks and then turn left ___ the corner.", options=["for; at","on; to","in; at","at; for"], correct=0),
    dict(q="It usually ___ Jay twenty minutes ___ his scooter to work.", options=["spends; riding","takes; rides","spends; to ride","takes; to ride"], correct=3),
    dict(q="The reporters were busy ___ the factory workers when the fire started again.", options=["interview","interviewed","interviewing","to interview"], correct=2),
    dict(q="The Browns ___ to have a picnic with us next weekend.", options=["go","were going","is going","are going"], correct=3),
    dict(q="A: ___ did it take you to get to the bus stop? B: About ten minutes.", options=["When","What time","How many","How long"], correct=3),
    dict(q="A: The jeans ___ NT$1,690. B: ___ not cheap. I don't want to spend that much money.", options=["pay; It's","spend; They're","cost; They're","cost; It's"], correct=2),
    dict(q="Let's go to the museum ___ metro. ___ a taxi costs too much.", options=["by; Taking","by; Get","on; Take","on; Getting"], correct=0),
    dict(q="A: ___ did you get to William's place last week? B: I drove my car.", options=["How","What","Why","How long"], correct=0),
    dict(q="There is going to ___ a basketball game at the park tomorrow.", options=["have","being","be","having"], correct=2),
  ]),
  dict(type="mc", title="三、對話選擇", meta="8分，每題2分", items=[
    dict(q="A: How much did that pair of pants cost? B: ___", options=["That's all, thanks.","It cost me NT$590.","The total is NT$390.","Here is one thousand dollars."], correct=1),
    dict(q="A: How do we get to Loren Hospital? B: ___", options=["I kept walking for forty minutes.","We took the metro and the bus.","Go down Sixth Street and turn left.","It will take half an hour to get there."], correct=2),
    dict(q="A: How would you like to pay? B: ___", options=["By card.","I'd like to pay for it.","I paid for it by card.","I'd spend one thousand on it."], correct=0),
    dict(q="A: How long did it take you to do the report? B: ___", options=["It cost us a lot.","I didn't take it.","It took me a week.","I spent a lot of money on it."], correct=2),
  ]),
  dict(type="guided", title="四、依提示作答", meta="12分，每題3分", items=[
    dict(prompt="How much are those blue shorts?", hint="（動詞用cost改寫）", answer="How much do those blue shorts cost?"),
    dict(prompt="May rides a scooter to the library every morning.", hint="（用by改寫交通方式）", answer="May goes to the library by scooter every morning."),
    dict(prompt="It took Ted one hour to drive to the elementary school.", hint="（用spend改寫）", answer="Ted spent one hour driving to the elementary school."),
    dict(prompt="Mr. Johnson spent fifty thousand dollars on the toy car.", hint="（動詞用pay改寫）", answer="Mr. Johnson paid fifty thousand dollars for the toy car."),
  ]),
  dict(type="translation", title="五、翻譯", meta="12分，每題3分", items=[
    dict(zh="走路到旅館要花多少時間？（on foot）", answer="How long / How much time does it take to get / go to the hotel on foot?"),
    dict(zh="她將不會付那麼多錢在一雙鞋子上。（pay）", answer="She won't / isn't going to pay that much money for a pair of shoes."),
    dict(zh="大多數人在那間百貨公司花很久的時間購物。", answer="Most people spend a long time shopping at that department store."),
    dict(zh="開車去工作通常花 Mike 一小時。（It...）", answer="It usually takes Mike an hour to drive to work."),
  ]),
  dict(type="cloze", title="六、克漏字選擇", meta="14分，每題2分", image="images/test11c/sec6_map.png",
    passage="Susan is in front of the flower shop. She wants to buy some gloves at the department store. She can walk ___1___ Kathy Road and turn ___2___ on Lindsay Street. The department store is ___3___ a bank.\n\nAllen just got ___4___ at the bus station on Lindsay Street. He is walking to the police station. He'll go straight ___5___ one block.\n\nBrenda is in the hotel. She is sick. To see a doctor, she needs to go down Jeremy Road and turn left on ___6___. The hospital is on her ___7___.",
    items=[
      dict(options=["in","from","across","along"], correct=3),
      dict(options=["up","left","down","right"], correct=1),
      dict(options=["next to","behind","between","across from"], correct=3),
      dict(options=["to","on","by","off"], correct=3),
      dict(options=["at","in","by","for"], correct=3),
      dict(options=["Kathy Road","Lindsay Street","Andrew Street","the block"], correct=2),
      dict(options=["left","right","front","back"], correct=1),
  ]),
  dict(type="reading", title="七、閱讀測驗", meta="12分，每題3分", passages=[
    dict(label="Spring Donation Drive", text="    Joy & Love is going to have its spring donation drive for people in Africa. We'd like you to donate your old shoes and clothes. However, please do not donate winter shoes, clothes, or gloves. People there won't need them because of the hot weather. Also, do not donate shoes like those in Picture 2.\nDonation time: March 1–14.\nDonation place: 2F, No. 15, Hill Rd., Hope City 116\n* Please send your donation to the above address or take it there during office hours from 10 a.m. to 6 p.m.\n* Please clean your old clothes and shoes before you donate them.\n    Besides clothes and shoes, we welcome cash donations. With your donation, we can help more people in Africa. Please call us at 0800-660-026 for any questions. Thank you for your donation!\n\n【字詞】donation drive 捐獻活動　donate 捐獻　address 地址　true 真實的", image="images/test11c/r_shoes.png",
      items=[
        dict(q="What is this reading about?", options=["A shoe sale.","A store for clothes.","Donations to people in Africa.","Donations of food and clothes."], correct=2),
        dict(q="Which is good to donate to Joy & Love's spring donation drive?", image="images/test11c/r_q2.png", options=["A","B","C","D"], correct=3),
        dict(q="Why DOESN'T Joy & Love want people to donate winter clothes?", options=["It's usually hot in Africa.","Winter clothes are ugly.","It's always sunny in Africa.","Winter clothes are not cheap."], correct=0),
        dict(q="Which is NOT true?", options=["The donation drive lasts for two weeks.","Joy & Love doesn't want bad shoes.","People can only donate clothes and shoes.","People can take their donation to the donation place."], correct=2),
      ]),
  ]),
]
