META = dict(n=13, h1="第13回・Review Test 4", subtitle="Unit 1～Unit 6 全冊總複習")
SECTIONS = [
  dict(type="mc", title="一、單題：請依文意選出一個正確或最佳的答案", meta="40分，每題2分", items=[
    dict(q="A: ___ the weather be like in London? B: It'll be rainy and cool.", options=["How's","What's","How will","What will"], correct=3),
    dict(q="A: May I speak to Mr. Thomas, please? B: ___", options=["Thanks a lot.","You're wrong.","This is she speaking.","Sorry. He is not here."], correct=3),
    dict(q="The girl ___ asleep right after she closed her eyes.", options=["falls","fell","is falling","will fall"], correct=1),
    dict(q="Wes drank some warm milk ___ he went to bed. It helped him to sleep.", options=["after","because","before","so"], correct=2),
    dict(q="The boy kept ___ the guitar. Finally, he became a great guitar player.", options=["practice","practicing","practiced","to practice"], correct=1),
    dict(q="A: Your violin is cool. Did it ___ you a lot? B: No. My parents bought it for me.", options=["cost","spend","take","pay"], correct=0),
    dict(q="When I got home, my mom and my sister ___ the windows.", options=["wipe","are wiping","was wiping","were wiping"], correct=3),
    dict(q="Uncle Leo has a dog, Lulu. He always ___ her to some snacks when she ___ a trick.", options=["treats; did","treated; does","treats; does","treats; was doing"], correct=2),
    dict(q="It took Sandy thirteen hours ___ from Taiwan to the USA.", options=["fly","to fly","flies","flew"], correct=1),
    dict(q="Going to the movies ___ a lot of fun for Jake.", options=["is","are","has","have"], correct=0),
    dict(q="A: What time did it start to rain? B: At about half ___ twelve.", options=["to","past","from","before"], correct=1),
    dict(q="Jessie wrote a postcard ___ from London（倫敦）when she went on vacation there. I was happy when I got the postcard.", options=["for me","from me","to me","me"], correct=2),
    dict(q="A: ___ shoes are they? B: Betty's. She bought them at a low price.", options=["What","Who","Whose","Which"], correct=2),
    dict(q="Liam's classmates ___ him because of his old pants. Liam was sad.", options=["made fun of","looked for","signed up for","heard about"], correct=0),
    dict(q="The park is close to our house. Let's go there ___ foot.", options=["on","with","in","of"], correct=0),
    dict(q="The man didn't say \"go die\" to you. ___, he said \"good day.\"", options=["Still","So","Finally","In fact"], correct=3),
    dict(q="I want to make a lot of money, and I hope to become a ___ businessman one day.", options=["heavy","successful","difficult","straight"], correct=1),
    dict(q="When I was in junior high school, history was my favorite ___.", options=["season","scooter","subject","soldier"], correct=2),
    dict(q="My brother wants to be a lawyer when he ___.", options=["gets off","comes off","cools down","grows up"], correct=3),
    dict(q="Come in, please. You can ___ up your coat on the rack（架子）.", options=["hold","hang","pull","leave"], correct=1),
  ]),
  dict(type="reading", title="二、題組：請依所附的短文或圖表，選出一個最適當的答案", meta="60分，每題3分", passages=[
    dict(start=21, label="A.（21～23）", text="Ryan: I'm going to visit the Palace Museum this Sunday.\nKate: The museum isn't in our city. How will you go there?\nRyan: I'll take the train first and then take a bus.\nKate: How much is the museum ticket?\nRyan: Three hundred and fifty dollars.\nKate: It's a little expensive.\nRyan: Yes, but I'm going to spend all day there seeing and learning new things.\nKate: Good for you!\n\n【字詞】ticket 票　true 真實的",
      items=[
        dict(q="What are Ryan and Kate talking about?", options=["Going hiking.","Taking the train.","Going shopping.","Visiting a museum."], correct=3),
        dict(q="How much will Ryan spend on the museum ticket?", options=["$50.","$300.","$315.","$350."], correct=3),
        dict(q="Which is true about Ryan's trip on Sunday?", options=["He'll go by car.","It'll take him half a day.","The ticket doesn't cost much.","He'll learn something new on the trip."], correct=3),
      ]),
    dict(start=24, label="B.（24～28）", text="    Good evening. I'm Sally Baldwin from JTV News. Let's take a look at next week's weather. From Monday to Wednesday, the temperature will be 14 to 17°C. It'll be a little windy. On Thursday, there will be a cold front. The temperature will go down to 9°C. There will be lots of rain on Friday, so be sure to take an umbrella with you when you go out. Luckily, the weather will <u>clear up</u> on Saturday. During the weekend, it'll be sunny, and the temperature will go back up to 18°C. So it'll be a great weekend to plan a trip. That's the weather from JTV News. Thanks for joining us and have a nice week!\n\n【字詞】news 新聞　temperature 溫度　cold front 冷鋒　most likely 最可能的",
      items=[
        dict(q="What is the reading about?", options=["A science lesson.","A weather report.","News about a country.","Making a plan for a trip."], correct=1),
        dict(q="How many rainy days will there be next week?", options=["One.","Two.","Three.","Four."], correct=0),
        dict(q="When the weather <u>clears up</u>, ___.", options=["it is rainy and windy all day","it stops raining and the sun comes out","it is sunny before lunch and then starts raining","it snows in the morning and then rains in the evening"], correct=1),
        dict(q="Which is true?", options=["It will be hot on Wednesday.","The temperatures will go up on the weekend.","The cold front will last for three days.","Sally Baldwin is interviewing someone on TV."], correct=1),
        dict(q="Which is most likely next week's weather?", image="images/test13c/q28_weather.png", options=["A","B","C","D"], correct=2),
      ]),
    dict(start=29, label="C.（29～32）", text="    Mrs. Martin works at a big company. She answers phone calls for her boss and helps with office work. She often works past her end time of 5:30, but today, she turned off her computer right on time—it was her son Ben's 14th birthday. She's taking him to a nice restaurant on the corner of Spring Road and Second Street. She'll take a bus after work and meet Ben there at a quarter past six. After dinner, they'll take the metro to a department store to get Ben a new pair of pants for his birthday. Mrs. Martin is a busy career woman, but she's also a great mom.\n\n【字詞】on time 準時",
      items=[
        dict(q="Look at the map. Which is the restaurant?", image="images/test13c/q29_map.png", options=["A.","B.","C.","D."], correct=3),
        dict(q="What is most likely Mrs. Martin's job?", options=["She's a dentist.","She's a bus driver.","She's a mail carrier.","She's an office worker."], correct=3),
        dict(q="What time did Mrs. Martin turn off her computer today?", options=["At five thirty.","After five thirty.","At half past six.","At a quarter to seven."], correct=0),
        dict(q="Which is true?", options=["Mrs. Martin will drive to the restaurant.","Mrs. Martin will buy a pair of pants for Ben.","Mrs. Martin and Ben will get home before 6 p.m.","Mrs. Martin and Ben will go shopping before dinner."], correct=1),
      ]),
  ]),
  dict(type="cloze", title="二、題組 D.（33～40）", meta="每題3分", start=33,
    passage="One day, a woman visited a bank with her five-year-old son. ___33___ she went to use the bathroom, a man in the bank took the boy. The man told a bank clerk, \"___34___ me all your money, or I'll shoot him.\" A bank clerk called the police. The police came ___35___, but they waited at first because they didn't want the man to hurt the boy. Then Officer Nelson started ___36___ to the man. Suddenly, a police officer shot the man, and he fell to the ___37___. The boy couldn't stop ___38___, so Officer Nelson had an idea. He said to everyone, \"It was just a rehearsal. Thank you for your help, kid!\" ___39___ His mother said yes. Then many police officers went to the boy and said, \"___40___\" The boy was very happy.\n\n【字詞】or 否則　shoot 射擊（過去式為shot）　suddenly 突然　rehearsal 演練",
    items=[
      dict(options=["When","Because","But","So"], correct=0),
      dict(options=["Buy","Give","Pay","Feed"], correct=1),
      dict(options=["soon","back","off","always"], correct=0),
      dict(options=["talk","talked","talking","and talking"], correct=2),
      dict(options=["bank","ground","drawer","truck"], correct=1),
      dict(options=["cries","cried","crying","to cry"], correct=2),
      dict(options=["The police took them to the police station.","The bank gave the boy money to thank him.","The boy said to the clerk, \"I'm happy to help.\"","The boy asked his mom, \"Was it just a rehearsal?\""], correct=3),
      dict(options=["I knew it!","It was you!","How interesting!","You did a great job!"], correct=3),
  ]),
]
