META = dict(n=2, h1="第2回・Unit 2", subtitle="You Can Learn About Game Design After You Join the Club")
SECTIONS = [
  dict(type="vocab", title="一、文意字彙", meta="20分，每題2分", items=[
    dict(q="A: Sorry, miss. You gave me the w___g order. B: I'm sorry. Here's the right one.", answer="wrong"),
    dict(q="Kathy is good with numbers; math isn't d___t for her at all.", answer="difficult"),
    dict(q="A: Do you speak Ch___e? B: Yes. It's my mother tongue（母語）.", answer="Chinese"),
    dict(q="My grandma isn't in good h___h. She's always sick.", answer="health"),
    dict(q="I was p___r at sports in school, so I didn't join any sports clubs.", answer="poor"),
    dict(q="My parents are computer e___rs at a big company. They design software（軟體）.", answer="engineers"),
    dict(q="Joseph is good at music; he can play the piano and the v___n.", answer="violin"),
    dict(q="This famous building is two hundred years old. There's a long h___y behind it.", answer="history"),
    dict(q="Can you take a picture of us with this c___a? Thank you!", answer="camera"),
    dict(q="A: The music f___l starts this week. Let's go together. B: Sure. I can see my favorite band there.", answer="festival"),
  ]),
  dict(type="mc", title="二、文法選擇", meta="20分，每題2分", items=[
    dict(q="After Nick looked for the perfect club for hours, he signed up for the movie club ___ the end of the day.", options=["for","in","on","at"], correct=3),
    dict(q="My sister usually ___ a glass of milk before she went to school. She doesn't do that now.", options=["drank","is drinking","drinking","drinks"], correct=0),
    dict(q="Tommy, you can go play at the playground. Call me ___ you need help.", options=["after","before","when","because"], correct=2),
    dict(q="Ms. Peters gave a great lesson ___ the mathematics behind magic today.", options=["for","on","to","over"], correct=1),
    dict(q="Their classroom is big and clean, but ours ___ small and dirty（髒的）.", options=["are","were","is","was"], correct=2),
    dict(q="After the lesson starts ___ talk to your classmates.", options=[", don't","never","don't",", not"], correct=0),
    dict(q="A: We need a soccer ball. B: You can borrow ___. He has one in his car.", options=["it","him","hers","John's"], correct=3),
    dict(q="A: Who's that woman over there? B: She's a cousin of ___.", options=["my","mine","I","me"], correct=1),
    dict(q="Tom, ___ your bed after you get up.", options=["makes","made","make","making"], correct=2),
    dict(q="John had a dinner party at eight, so he finished all his work before ___.", options=["he goes out","then","joined the party","he made up his mind"], correct=1),
  ]),
  dict(type="mc", title="三、對話選擇", meta="8分，每題2分", items=[
    dict(q="A: Is Megan in today? B: Sorry. ___ There's no Megan here.", options=["Please hold on.","She's inside right now.","She's not in the office.","You have the wrong number."], correct=3),
    dict(q="A: Hello, may I speak to Danny, please? B: ___ He's in the bathroom.", options=["I don't speak English.","This is he.","Can you call back?","You are speaking."], correct=2),
    dict(q="A: Are you still thinking about the color for the wall? B: No. ___ Blue is my choice.", options=["I made up my mind.","I think the same.","I'm pulling your leg.","You're not wrong at all."], correct=0),
    dict(q="A: Whose cool car is that? B: ___", options=["It's theirs.","That's Ms. Lee.","It's on the street.","You can say that again."], correct=0),
  ]),
  dict(type="guided-multi", title="四、依提示填入正確的動詞形式", meta="5分，每題1分", items=[
    dict(zh="(hear)", lines=["I {{heard}} a strange noise（聲響）after I walked into the old house."]),
    dict(zh="(get)", lines=["Ava was very happy when she {{got}} a box of chocolate from me."]),
    dict(zh="(teach)", lines=["Ray {{taught}} PE when he was twenty-eight."]),
    dict(zh="(play)", lines=["Martha {{plays}} soccer when the weather is nice."]),
    dict(zh="(end)", lines=["Please finish your painting before the class {{ends}}."]),
  ]),
  dict(type="cloze", title="五、克漏字選擇", meta="14分，每題2分",
    passage="Lucy: Hello. ___1___ Who is this?\nBen: Hi, Lucy. ___2___ Can you get some cookies for me later?\nLucy: I can't. Today is Friday. I have piano class.\nBen: Can't you stop at Nitta's Shop ___3___ you go to class? Or go during your break? I love the cookies from the shop.\nLucy: It's not on the way. Also, my break is short. I can't go and come ___4___ in time.\nBen: How about after you ___5___ the class?\nLucy: No. Why don't you get the cookies ___6___? You have time.\nBen: You're right. I can go. Why didn't I ___7___ that? Do you want some? I can get some for you.\nLucy: Sure, get me five.\n\n【字詞】break 休息時間　in time 及時",
    items=[
      dict(options=["This is Lucy.","Who's speaking?","May I speak to Ben?","You have the wrong number."], correct=0),
      dict(options=["This is Ben.","What's up?","See you later.","Nice to meet you."], correct=0),
      dict(options=[", but","after","before","because"], correct=2),
      dict(options=["by","just","back","soon"], correct=2),
      dict(options=["start","call","finish","hear"], correct=2),
      dict(options=["on call","in the end","in a fun way","on your own"], correct=3),
      dict(options=["miss out","hold on","hear about","think of"], correct=3),
  ]),
  dict(type="reading", title="六、閱讀測驗", meta="12分，每題4分", passages=[
    dict(label="", text="Mike reserved a book, and now he is checking it out from TCL Library. He's new to this library, so he read the steps before he came.\n\nStep 1: Use Computer D1 with your TCL library card.\nStep 2: After you enter the name of the book into the computer, you get a number. That's your book number.\nStep 3: Go to Table C2 and look for your book. All books have a white card with the book number on them.\nStep 4: After you get your book at Table C2, put the white card in the black box by Table C2.\nStep 5: Go to Computer B7 and put the barcode of your book under the sensor.\nAfter the sensor reads the barcode of your book, you can take the book home for a week. Enjoy your time with the book!\n\n【字詞】reserve 預約　step 步驟　enter 輸入　barcode 條碼　sensor 感應器",
      items=[
        dict(q="Mike just walked into the library. What does he do first?", options=["Go to Table C2.","Go to Computer B7.","Look for Computer D1.","Put his card into a black box."], correct=2),
        dict(q="What does Mike do after he has the book number?", options=["Go to Computer B7.","Get his book at Table C2.","Write it down on a white card.","Check the barcode on the book."], correct=1),
        dict(q="Mike just finished step 4. What does he need for the next step?", options=["Only the book.","The white card.","The white card and the book.","The white card, the book, and his library card."], correct=0),
      ]),
  ]),
  dict(type="guided", title="七、依提示作答", meta="9分，每題3分", items=[
    dict(prompt="I got this robot for free when I signed up for the contest.", hint="（用When...改寫）", answer="When I signed up for the contest, I got this robot for free."),
    dict(prompt="He called his friend. / Then he started his guitar lesson.", hint="（用... after...合併）", answer="He started his guitar lesson after he called his friend."),
    dict(prompt="My parents and <u>your parents</u> went to the same school.", hint="（畫線部分改為所有格代名詞）", answer="My parents and yours went to the same school."),
  ]),
  dict(type="translation", title="八、翻譯", meta="12分，每題4分", items=[
    dict(zh="這些是誰的夾克？", answer="Whose jackets are these?"),
    dict(zh="在你吃午餐之前，洗你的手。", answer="Wash your hands before you eat / have lunch. / Before you eat / have lunch, wash your hands."),
    dict(zh="科學是一門有趣的學科。", answer="Science is an interesting / a fun subject."),
  ]),
]
