META = dict(n=9, h1="第9回・Unit 5", subtitle="How Do We Go to the Hotel?")
SECTIONS = [
  dict(type="vocab", title="一、文意字彙", meta="20分，每題2分", items=[
    dict(q="It was raining, so I didn't ride my m___e to work. I took a bus.", answer="motorcycle"),
    dict(q="<i>Romeo and Juliet</i> is a famous p___y by Shakespeare.", answer="play"),
    dict(q="The kite fell to the g___d when the wind stopped.", answer="ground"),
    dict(q="My parents are both doctors. That work at this h___l.", answer="hospital"),
    dict(q="I put a b___l on my cat, so I can hear her when she walks around.", answer="bell"),
    dict(q="A: Excuse me, s___r. Are you ready to order? B: I'm sorry, but I'm a woman, not a man.", answer="sir"),
    dict(q="Sophie sometimes h___ts her head on the doorframe（門框）because she's too tall.", answer="hits"),
    dict(q="It was too hot, so Joe jumped into the swimming p___l and started swimming.", answer="pool"),
    dict(q="Can you get some stamps（郵票）at the p___t office for me?", answer="post"),
    dict(q="They are building a f___e to cook dinner next to their camp.", answer="fire"),
  ]),
  dict(type="mc", title="二、文法選擇", meta="20分，每題2分", items=[
    dict(q="I love going ___ on cold days like today.", options=["jog","jogging","jogged","and jogging"], correct=1),
    dict(q="Angela is a pilot（機師）. Her job is to ___ an airplane to different cities every other day.", options=["buy","take","fly","ride"], correct=2),
    dict(q="We're late for work. We can't ___ metro to the office now.", options=["ride","take","take a","take the"], correct=3),
    dict(q="Stacy's office is ___ the corner ___ King Street and Magic Road.", options=["at; on","on; of","in; of","on; on"], correct=1),
    dict(q="A: Where's the restaurant? B: It's on the floor above. Just go ___ the stairs over there.", options=["on","above","down","up"], correct=3),
    dict(q="Be ready. We need to get ___ the train at the next stop.", options=["off","to","on","down"], correct=0),
    dict(q="The coffee shop across ___ my school sells great hot chocolate.", options=["with","by","from","to"], correct=2),
    dict(q="A: Where does this toy go? B: You can put it in the third drawer ___ your right.", options=["of","with","in","on"], correct=3),
    dict(q="I didn't hear you then because I was busy ___ my science report.", options=["did","doing","to do","do"], correct=1),
    dict(q="A: How can we get to the library? B: It's close. Let's go there by ___.", options=["plane","a bus","scooter","ships"], correct=2),
  ]),
  dict(type="mc", title="三、對話選擇", meta="6分，每題2分", items=[
    dict(q="A: Did you enjoy surfing for the first time? B: I had a wonderful time. ___", options=["A ship almost hit me.","What great fun!","The mountain was beautiful.","I was lost in the sea."], correct=1),
    dict(q="A: ___ I'm looking for the school office. B: You're in the right place. What can I do for you?", options=["Hold on a minute.","Excuse me.","How can I get to school?","What can we do later?"], correct=1),
    dict(q="A: How can I get to the metro station from here? B: ___", options=["Go straight and then turn right.","It is easy to go there on foot.","It's between a park and a museum.","There are many bus stops near the station."], correct=0),
  ]),
  dict(type="cloze", title="四、克漏字選擇【A】", meta="8分，每題2分",
    passage="Tom likes nature, so he moved into a big house right next to a forest in the countryside. He can go to the forest on ___1___ and enjoy the beautiful view along the walk. Sometimes, there are even birds singing. It is a wonderful ___2___ to join nature's concert. There's a lake ___3___ the forest. In his free time, he likes to go ___4___ in the clean water. Tom loves his life in the countryside.\n\n【字詞】nature 自然　countryside 鄉下　view 風景",
    items=[
      dict(options=["foot","toy","scooter","bus"], correct=0),
      dict(options=["hope","dream","country","experience"], correct=3),
      dict(options=["along","above","next to","between"], correct=2),
      dict(options=["biking","hiking","sailing","swimming"], correct=3),
  ]),
  dict(type="cloze", title="四、克漏字選擇【B】", meta="10分，每題2分", start=5,
    passage="(On the street)\nPam: Where are we? I can't find the street on the ___5___.\nJeff: Let's ask the man over there ___6___ help.\nPam: Excuse me. We are lost. ___7___\nMan: Just go ___8___ the river bank. Turn right on First Street and go straight for two blocks. The hotel is on your right. Or ___9___. There's a bus stop over there.",
    items=[
      dict(options=["pool","map","ground","corner"], correct=1),
      dict(options=["to","with","for","from"], correct=2),
      dict(options=["Where are you from?","How can we get to Joy Hotel?","Is there a metro station nearby?","How do you usually go to the hotel?"], correct=1),
      dict(options=["by","between","along","across"], correct=2),
      dict(options=["you can go on foot","I can drive you there","I can show you the way","you can take a bus there"], correct=3),
  ]),
  dict(type="reading", title="五、閱讀測驗", meta="15分，每題3分", passages=[
    dict(label="【A】Lisa sees her friend Kevin in front of her house.", text="Lisa: Hey, Kevin. What's up?\nKevin: I'm going to the supermarket, but I don't remember the way there. Can you help me?\nLisa: Of course. Go down this road and turn left on First Street. It's on your right.\nKevin: Thank you. By the way, is there a bank near the supermarket?\nLisa: Yes, there's one ______.\nKevin: Okay. Thanks a lot.", image="images/test9b/r_map.png",
      items=[
        dict(q="Which is the supermarket?", options=["A.","B.","C.","D."], correct=2),
        dict(q="What might be in the blank（空格）?", options=["on Market Road","right next to the metro station","between the temple and the police station","on the corner of Easy Road and First Street"], correct=3),
        dict(q="<div style=\"background:#fff;border:1px solid var(--paper-line);border-radius:8px;padding:10px 14px;font-style:italic;margin-bottom:8px;\">It's easy to get to Sunny Day. When you come out of the metro station on Second Street, turn right and you can see a beautiful building right across the road. That's us.</div>What is Sunny Day?", options=["A temple.","A bank.","A hotel.","A police station."], correct=2),
      ]),
    dict(label="【B】This is Jerry's schedule at Aloha Summer Camp.", text="",
      table=dict(title="Aloha Summer Camp", head=["Time","Mon. to Wed.","Thurs. to Sat.","Sun."], rows=[
        ["9:00–11:00","Camping","Biking","Hiking"],
        ["11:00–12:00","Jogging","Dancing","Games"],
        ["12:00–13:00","Lunch","Lunch","Lunch"],
        ["13:00–14:00","Swimming","Picnicking","Sailing"],
        ["14:00–17:00","Surfing","Cooking lessons","Mountain climbing"]],
        note="【字詞】schedule 行程表"),
      items=[
        dict(q="Jerry did water activities all afternoon. What did he do in the morning?", options=["He went camping.","He went biking.","He went mountain climbing.","He went dancing."], correct=0),
        dict(q="It's 1:25 p.m. on Friday. Which is true（真實的）?", options=["Jerry is at the beach.","Jerry is having a picnic.","Jerry went hiking in the morning.","Jerry just finished a cooking lesson."], correct=1),
      ]),
  ]),
  dict(type="guided", title="六、依提示作答", meta="9分，每題3分", items=[
    dict(prompt="What do you like to do in your free time?", hint="（用「去購物」詳答）", answer="I like to go shopping in my free time."),
    dict(prompt="Henry went to the library <u>by bike</u>.", hint="（依畫線部分造原問句）", answer="How did Henry go to the library?"),
    dict(prompt="Claire goes to work by scooter every day.", hint="（用ride改寫）", answer="Claire rides a scooter to work every day."),
  ]),
  dict(type="translation", title="七、翻譯", meta="12分，每題4分", items=[
    dict(zh="我們搭計程車去那間書店吧。", answer="Let's go to the bookstore by taxi. / Let's take a taxi to the bookstore."),
    dict(zh="直走兩個街區並在你看到一間餐廳時左轉。", answer="Go straight for two blocks and turn left when you see a restaurant."),
    dict(zh="Jane 正在她床上的角落修理一個玩具。", answer="Jane is fixing a toy on the corner of her bed. / Jane is sitting on the corner of her bed and fixing a toy."),
  ]),
]
