META = dict(n=13, h1="第13回・Review Test 4", subtitle="Unit 1～Unit 6 全冊總複習")
SECTIONS = [
  dict(type="mc", title="一、單題", meta="40分，每題2分", items=[
    dict(q="Look at the picture. The boy is ___.", image="images/test13b/q1.png", options=["mad","lost","wrong","kind"], correct=1),
    dict(q="The bag isn't heavy at all. ___, there's nothing inside.", options=["In fact","Finally","However","What's more"], correct=0),
    dict(q="Carl is good at selling cars. He sold twenty last month. He's a born ___.", options=["secretary","lawyer","salesman","reporter"], correct=2),
    dict(q="Ms. Smith is my favorite teacher. Her ___ have songs and games and are always interesting.", options=["ideas","lessons","interviews","dreams"], correct=1),
    dict(q="My math homework is too ___. Can you help me with it?", options=["funny","expensive","high","difficult"], correct=3),
    dict(q="You don't need to ___ me, sir. This hat is free.", options=["leave","pay","hear","feed"], correct=1),
    dict(q="A: How was the weather this morning? B: It ___ when I woke up, but it stopped soon after.", options=["snows","snowed","was snowing","will snow"], correct=2),
    dict(q="I was so scared when I was in that old house. It was a ___ experience.", options=["successful","wonderful","terrible","heavy"], correct=2),
    dict(q="A: Excuse me. How do I get to the temple? B: Go down this road for a ___. You will see it on your right.", options=["corner","floor","ground","block"], correct=3),
    dict(q="Can you ___ my toy robot, please? It fell to the floor, and the right arm came off.", options=["fix","find","break","catch"], correct=0),
    dict(q="It ___ me one hundred dollars ___ this cup of green tea.", options=["cost; buying","spent; to buy","cost; to buy","spent; buying"], correct=2),
    dict(q="A: What do you plan ___ doing this summer vacation? B: I decided ___ in a bookstore.", options=["to; to work","on; working","on; to work","to; working"], correct=2),
    dict(q="A: How do I get to the bank from my house? B: You can ___.", options=["go to the bank","take the metro there","turn left on Red Street","get money at the bank"], correct=1),
    dict(q="I love cooking. Making my family three meals a day ___ easy for me.", options=["were","was","are","is"], correct=3),
    dict(q="Warren loves his cats very much. He spends half an hour ___ them every day.", options=["dressed","to dress","dress","dressing"], correct=3),
    dict(q="___ your breakfast before you go to the park. You can't play on an empty（空的）stomach.", options=["Finishing","Finish","To finish","Finishes"], correct=1),
    dict(q="Emily ___ me ___ this beautiful painting. In fact, she spent all night working on it.", options=["showed; ×","showed; to","made; ×","made; for"], correct=3),
    dict(q="I will go to the post office before I ___ you. I need to mail something to my brother first.", options=["meet","met","will meet","am meeting"], correct=0),
    dict(q="Martha doesn't enjoy ___ in the mountains at all. She likes to sit and read.", options=["go hiking","going hiking","to go hiking","going to hike"], correct=1),
    dict(q="A: Are you all right? B: No. I need someone ___ to.", options=["talking","talk","and talk","to talk"], correct=3),
  ]),
  dict(type="cloze", title="二、題組（21－24）", meta="12分，每題3分", start=21,
    passage="Last Saturday morning, Mindy made breakfast for her parents because she enjoyed ___21___ nice things for them. She woke her parents up at nine o'clock ___22___. Then they had the food together. At ___23___, Mindy was doing the dishes. After she finished, she was happy and kept going with her day. To Mindy, having a great breakfast with her parents is a good way to ___24___ the day.",
    items=[
      dict(options=["do","did","to do","doing"], correct=3),
      dict(options=["before she called them","when she was eating breakfast","after she made some sandwiches","because she wanted to go jogging"], correct=2),
      dict(options=["half past nine","a quarter to nine","the moment","night"], correct=0),
      dict(options=["grow","start","lend","become"], correct=1),
  ]),
  dict(type="cloze", title="二、題組（25－32）", meta="24分，每題3分", start=25,
    passage="Ned: Whose postcard is this on the coffee table?\nPete: ___25___ Michelle sent the postcard ___26___ me.\nNed: Right, she's taking a ___27___ in London. What's the weather ___28___ over there?\nPete: It's usually rainy. Luckily, it was ___29___ during her trip.\nNed: She'll be back tomorrow. Are you going to do something special with her ___30___? Valentine's Day is this Sunday.\nPete: What do you ___31___? She's not my girlfriend.\nNed: But don't you want her to be? This is your chance.\nPete: ___32___ Maybe I'll ask her out to dinner.\n\n【字詞】Valentine's Day 情人節　chance 機會",
    items=[
      dict(options=["It's me.","It's over there.","It's mine.","It's Michelle's."], correct=3),
      dict(options=["to","at","for","from"], correct=3),
      dict(options=["tip","map","choice","vacation"], correct=3),
      dict(options=["like","×","doing","going"], correct=0),
      dict(options=["fun","rainy","warm","sunny"], correct=3),
      dict(options=["right now","this weekend","a week later","the day before yesterday"], correct=1),
      dict(options=["ask","speak","mean","believe"], correct=2),
      dict(options=["Have fun.","Great job.","Good idea.","Take it easy."], correct=2),
  ]),
  dict(type="reading", title="二、題組（33－40）", meta="24分，每題3分", passages=[
    dict(start=33, label="（33－36）", text="Ryan: Hello, this is Ryan's Healthy Food. How may I help you?\nJodie: Hi. I'd like to have a dinner party at your restaurant this Friday. However, I always drive there, so I only know the way there by car. Are there any other ways to get there?\nRyan: Of course. Besides coming by car, you can take Bus 89 or Bus Red 13 and get off at Fifth Street. The bus stop is in front of our front door. However, it will take more time to get here after five o'clock because of the traffic. Or you can take the metro and get off at Bond Street Station. Walk straight for around five minutes and turn left when you see an old hospital. Walk for two minutes, and you'll see our restaurant on your right. You can also take the train to Oliver Street Station and take the shuttle bus to the department store across from us. It's free.\nJodie: OK. Thank you so much for your help.\n\n【字詞】traffic 交通　shuttle bus 接駁車",
      items=[
        dict(q="Why is Jodie calling Ryan?", options=["To order food for dinner.","To ask him to come to her party.","To borrow a car from him.","To ask about ways to get to his restaurant."], correct=3),
        dict(q="<div style=\"background:#fff;border:1px solid var(--paper-line);border-radius:8px;padding:10px 14px;font-style:italic;margin-bottom:8px;\">Hey, Jodie. I'll be a little late. The traffic around the restaurant is really bad. Sorry!</div>Eve, Jodie's friend, sent this message（訊息）to Jodie. Which COULDN'T Eve be taking to the restaurant?", options=["A train.","A bus.","The metro.","A taxi."], correct=0),
        dict(q="What CAN'T we infer（推論）from the talk?", options=["Jodie can drive a car.","Ryan's Healthy Food is on Fifth Street.","Jodie went to Ryan's Healthy Food before.","Ryan's Healthy Food is close to Oliver Street Station."], correct=1),
        dict(q="Jodie just got off at Bond Street Station. Which is the right map?", image="images/test13b/q36_maps.png", options=["A","B","C","D"], correct=3),
      ]),
    dict(start=37, label="（37－40）", text="Yesterday was June 1. Evan and Rachel went shopping at Woody's Clothes Shop. Evan got two pairs of jeans, but he only needed to pay for one because of the sale. Rachael got five T-shirts, a skirt, and a coat. Rachel spent 1,620 dollars in total. She saved a lot of money. She saved three hundred and twenty dollars on the skirt alone.\n\n【字詞】50% off 打五折　alone 單獨地", image="images/test13b/q37_flyer.png",
      items=[
        dict(q="What can we learn from the flyer（傳單）?", options=["Skirts and dresses have the same price.","People can get everything for half price at the sale.","The sale at Woody's Clothes Shop will last for a week.","People can buy three ties for the price of one pair of shorts."], correct=3),
        dict(q="How much did Rachel spend on the skirt?", options=["Six hundred dollars.","Six hundred and forty dollars.","Three hundred and forty dollars.","Three hundred and twenty dollars."], correct=3),
        dict(q="What does it mean when jeans are \"<u>BOGOF</u>\"?", options=["You get a pair for free.","You get a pair at a high price.","You get two pairs for the price of one.","You need to get three pairs at the same time."], correct=2),
        dict(q="Rachel's sister has a thousand dollars. What can she buy at Woody's on June 5?", options=["A jacket and a tie.","A coat and a jacket.","Four T-shirts and a coat.","Five shirts and a pair of shorts."], correct=0),
      ]),
  ]),
]
